# Use postgres/example user/password credentials

services:
  # db:
  #   image: postgres:17
  #   # restart: always
  #   # set shared memory limit when using docker compose
  #   shm_size: 128mb
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - '5432:5432'

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000' # S3 API
      - '9001:9001' # Web console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  # postgres-data:
  #   driver: local

  minio-data:
